"""
Artist nationality / origin classification (UK domestic vs. International).

Methodology note (documented for the research paper): classification is based
on the artist's/act's country of origin or primary billed nationality
(publicly known biographical fact), not label or chart territory. Acts that
are genuinely of mixed/uncertain origin, non-musical credits (soundtracks,
media brands, ambience tracks), or names too obscure to verify confidently
are labeled "Unclassified" rather than guessed, and are reported as their own
transparent category rather than silently folded into UK or International.
"""

UK = "UK / Domestic"
INTL = "International"
UNK = "Unclassified"

NATIONALITY = {
    # --- Global top artists ---
    "Taylor Swift": INTL, "Sabrina Carpenter": INTL, "Billie Eilish": INTL,
    "Olivia Rodrigo": INTL, "Chappell Roan": INTL, "Benson Boone": INTL,
    "Central Cee": UK, "Drake": INTL, "The Killers": INTL, "Dua Lipa": UK,
    "Chase & Status": UK, "Noah Kahan": INTL, "RAYE": UK, "Teddy Swims": INTL,
    "Arctic Monkeys": UK, "The Weeknd": INTL, "D-Block Europe": UK,
    "Tate McRae": INTL, "Dave": UK, "Ariana Grande": INTL, "cassö": UK,
    "Harry Styles": UK, "Hozier": INTL, "Natasha Bedingfield": UK,
    "Vance Joy": INTL, "Charli xcx": UK, "Lord Huron": INTL,
    "Post Malone": INTL, "Ella Henderson": UK, "Michael Marcagi": INTL,
    "SZA": INTL, "Doja Cat": INTL, "Dasha": INTL, "Jazzy": INTL,
    "Ice Spice": INTL, "Kanye West": INTL, "Coldplay": UK,
    "David Guetta": INTL, "David Kushner": INTL, "Beyoncé": INTL,
    "Tyla": INTL, "Shaboozey": INTL, "Fred again..": UK,
    "Clementine Douglas": UK, "Myles Smith": UK, "Madonna": INTL,
    "Bou": UK, "Kenya Grace": UK, "Rudimental": UK, "Kendrick Lamar": INTL,
    "Calvin Harris": UK, "OneRepublic": INTL, "Flowdan": UK, "Artemas": UK,
    "Sonny Fodera": INTL, "The Goo Goo Dolls": INTL, "Mitski": INTL,
    "Gunna": INTL, "Tyler, The Creator": INTL, "Zach Bryan": INTL,
    "Eminem": INTL, "Mark Ambor": INTL, "Gracie Abrams": INTL,
    "Travis Scott": INTL, "Richy Mitch & The Coal Miners": INTL,
    "Jack Harlow": INTL, "Djo": INTL, "Miley Cyrus": INTL, "Peggy Gou": INTL,
    "Tommy Richman": INTL, "The Kid LAROI": INTL, "Becky Hill": UK,
    "Lewis Capaldi": UK, "Fleetwood Mac": UK, "CamrinWatsin": UK,
    "bbyclose": UK, "BL3SS": UK, "Ty Dolla $ign": INTL, "RoRo": UK,
    "Hannah Laing": UK, "Bruno Mars": INTL, "Metro Boomin": INTL,
    "J Hus": UK, "Ellie Goulding": UK, "D.O.D": UK, "Oasis": UK,
    "Jordan Adetunji": UK, "Stormzy": UK, "PinkPantheress": UK,
    "Lady Gaga": INTL, "Rema": INTL, "MK": INTL, "Anne-Marie": UK,
    "Charlotte Plank": UK, "Vibe Chemistry": UK, "Sophie Ellis-Bextor": UK,
    "Obongjayar": UK, "Tom Odell": UK, "Morgan Wallen": INTL, "¥$": INTL,
    "Keinemusik": INTL, "Adam Port": INTL, "The Blessed Madonna": INTL,
    "Stryv": UNK, "Switch Disco": UK, "Robert Miles": INTL,
    "Nicki Minaj": INTL, "Frank Ocean": INTL, "Jorja Smith": UK,
    "Aqua": INTL, "Gigi Perez": INTL, "Future": INTL,
    "Florence + The Machine": UK, "Libianca": INTL, "21 Savage": INTL,
    "Billy Gillies": UK, "Hannah Boleyn": UK, "Linkin Park": INTL,
    "Playboi Carti": INTL, "Lil Baby": INTL, "Troye Sivan": INTL,
    "Nathan Dawe": UK, "Joel Corry": UK, "YG Marley": INTL,
    "Michael Bublé": INTL, "Bryson Tiller": INTL, "Good Neighbours": UK,
    "*NSYNC": INTL, "Mariah Carey": INTL, "Wham!": UK, "Kelly Clarkson": INTL,
    "Kygo": INTL, "Ava Max": INTL, "Tears For Fears": UK,
    "One Direction": UK, "Badger": UK, "Sam Smith": UK, "Jung Kook": INTL,
    "Coi Leray": INTL, "Abel Balder": INTL, "ANOTR": INTL, "Flo Milli": INTL,
    "Ndotz": UK, "Burna Boy": INTL, "Elton John": UK, "J. Cole": INTL,
    "Ed Sheeran": UK, "Addison Rae": INTL, "Brenda Lee": INTL,
    "Bobby Helms": INTL, "Lil Durk": INTL, "Latto": INTL,
    "Flatland Cavalry": INTL, "Rachel Zegler": INTL, "Bebe Rexha": INTL,
    "Loreen": INTL, "The Neighbourhood": INTL, "Andy Williams": INTL,
    "Lay Bankz": INTL, "Kylie Minogue": INTL, "The Last Dinner Party": UK,
    "The Pogues": UK, "Sam Fender": UK, "Bakar": UK, "Zara Larsson": INTL,
    "JENNIE": INTL, "Lily-Rose Depp": INTL, "Jungle": UK, "Mark Ronson": UK,
    "Dean Martin": INTL, "Hanumankind": INTL, "Kalmi": UNK,
    "FIFTY FIFTY": INTL, "Sia": INTL, "ROSÉ": INTL, "Shakin' Stevens": UK,
    "Ryan Gosling": INTL, "The Ronettes": INTL, "Marvin Gaye": INTL,
    "Tammi Terrell": INTL, "The Cranberries": INTL, "Band Aid": UK,
    "John Lennon": UK, "Paul McCartney": UK, "Chris Rea": UK, "KSI": UK,
    "LF SYSTEM": UK, "Justin Bieber": INTL, "Frank Sinatra": INTL,
    "Lana Del Rey": INTL, "Trippie Redd": INTL, "Nat King Cole": INTL,
    "Kings of Leon": INTL, "Wizzard": UK, "Pozer": UK,
    "José Feliciano": INTL, "Leona Lewis": UK, "Slade": UK,
    "Darlene Love": INTL, "The Jackson 5": INTL, "Kali": UNK,
    "Laufey": INTL, "Tom Grennan": UK, "Shania Twain": INTL, "JID": INTL,
    "Lizzy McAlpine": INTL, "JADE": UK, "Dominic Fike": INTL,
    "Van Morrison": UK, "Nines": UK, "Crowded House": INTL,
    "Fred Astaire": INTL, "Oliver Anthony Music": INTL, "Miguel": INTL,
    "Bing Crosby": INTL, "Burl Ives": INTL, "Fredo": UK,
    "Glass Animals": UK, "Mae Stephens": UK, "ArrDee": UK, "Bad Bunny": INTL,
    "Hedex": UK, "Journey": INTL, "Jimin": INTL, "Chuck Berry": INTL,
    "venbee": UK, "Pretenders": UK, "goddard.": UK, "The Beatles": UK,
    "The Beach Boys": INTL, "Cher": INTL, "Slay": UK, "Jonas Brothers": INTL,
    "Käärijä": INTL, "Elvis Presley": INTL, "Lil Mabu": INTL, "Mud": UK,
    "Eartha Kitt": INTL, "Jozzy": INTL, "Two Door Cinema Club": UK,
    "Baddiel": UK, "Lightning Seeds": UK, "Skinner": UK, "Cynthia Erivo": UK,
    "Bring Me The Horizon": UK, "Byron Messia": INTL,
    "Wicked Movie Cast": UNK, "Lizzo": INTL, "Mason": UNK,
    "Princess Superstar": INTL, "Alessandra": UNK, "Selena Gomez": INTL,
    "GRM Daily": UK, "Britney Spears": INTL, "Quavo": INTL, "NewEra": UNK,
    "WALK THE MOON": INTL, "Otis Redding": INTL, "Megan Thee Stallion": INTL,
    "Ocean Alley": INTL, "Clavish": UK, "Big Sean": INTL,
    "The Lightning Seeds": UK, "Anderson .Paak": INTL, "Perrie": UK,
    "Lorde": INTL, "Bill Withers": INTL, "CHIKA": INTL, "BabyTron": INTL,
    "Tina Turner": INTL, "Interplanetary Criminal": UK, "Nemo": INTL,
    "Luke Combs": INTL, "Anitta": INTL, "Various Artists": UNK,
    "Eliza Rose": UK, "Michael Jackson": INTL, "Rihanna": INTL,
    "Lyrical Lemonade": INTL, "Baby Sleeps": UNK, "Alex Warren": INTL,
    "Bruce Springsteen": INTL, "Perry Como": INTL, "Earth, Wind & Fire": INTL,
    "Donny Hathaway": INTL, "Dream Supplier": UNK, "sped up + slowed": UNK,
    "Stevie Wonder": INTL, "Blake Shelton": INTL, "XG": INTL,
    "Juliera": UNK, "Background White Noise": UNK, "Joost": INTL,
    "Jona Lewie": UK, "Flex (UK)": UK, "Busta Rhymes": INTL,
    "Whitney Houston": INTL, "Toploader": UK, "Hotvibez": UNK, "JVKE": INTL,
    "ABBA": INTL, "Baby Lasagna": INTL, "Andrew Gold": INTL,
    "Lil Uzi Vert": INTL, "Elesia Iimura": UNK, "Mae Muller": UK,
    'Bobby "Boris" Pickett & The Crypt-Kickers': INTL, "Nate Dogg": INTL,
    "Eagles": INTL, "Chris Brown": INTL, "O.T": UNK, "Atomic Kitten": UK,
    "Brett Eldredge": INTL, "Skepta": UK, "Black Eyed Peas": INTL,
    "Ray Parker Jr.": INTL, "Paris Paloma": UK, "Offset": INTL,
    "Outkast": INTL, "Headie One": UK, "a-ha": INTL, "Young Thug": INTL,
    "BTS": INTL, "Tracy Chapman": INTL, "K-Trap": UK, "Fat Les": UK,
    "Flo Rida": INTL, "The Verve": UK, "Tems": INTL, "Gala": INTL,
    "Lost Frequencies": INTL, "leftovermax": UNK, "Rockwell": INTL,
    "Sinéad O'Connor": INTL, "R3load": UK, "Neil Diamond": INTL,
    "New Order": UK, "LEXMENDY": UNK, "blink-182": INTL, "It's Nique": UNK,
    "Arcane": UNK, "BERKO CHAMP": UNK, "Tiakola": INTL,
    "Fontaines D.C.": INTL, "Liam Payne": UK, "Declan McKenna": UK,
    "Noa Kirel": INTL, "George Ezra": UK, "Pomme": INTL, "Niall Horan": INTL,
    "Rick James": INTL, "The Adventures Of Stevie V": UK, "Stromae": INTL,
    "Catfish and the Bottlemen": UK, "Stephen Sanchez": INTL,
    "The Lumineers": INTL, "The Kooks": UK, "citosxd": UNK, "4batz": INTL,
}


def classify(name: str) -> str:
    return NATIONALITY.get(name, UNK)
