"""
Generates static chart images (PNG) for the research paper / executive summary.
The live Streamlit dashboard renders its own interactive versions of most of
these from the same underlying data.
"""
import sys
sys.path.insert(0, "src")
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import networkx as nx

import analytics as an
from artist_nationality import classify

plt.rcParams.update({
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "font.size": 11,
    "axes.spines.top": False,
    "axes.spines.right": False,
})

ATLANTIC_NAVY = "#0B1F3A"
ATLANTIC_RED = "#E4572E"
ATLANTIC_GOLD = "#D9A441"
ATLANTIC_TEAL = "#2C7873"
ATLANTIC_GREY = "#8A94A6"
PALETTE = [ATLANTIC_NAVY, ATLANTIC_RED, ATLANTIC_GOLD, ATLANTIC_TEAL, ATLANTIC_GREY]

OUT = "outputs/figures"

df = pd.read_parquet("data/clean_playlist.parquet")
exploded = pd.read_parquet("data/exploded_artists.parquet")


def savefig(fig, name):
    fig.tight_layout()
    fig.savefig(f"{OUT}/{name}.png", dpi=180, bbox_inches="tight")
    plt.close(fig)
    print("saved", name)


# 1. Top dominating artists
top = an.top_dominating_artists(exploded, 15).sort_values()
fig, ax = plt.subplots(figsize=(8, 6))
ax.barh(top.index, top.values, color=ATLANTIC_NAVY)
ax.set_xlabel("Chart appearances (entry-days)")
ax.set_title("Top 15 Dominating Artists — UK Top 50 (May 2024–Nov 2025)")
savefig(fig, "01_top_artists")

# 2. Artist concentration (Lorenz-style cumulative share)
counts = an.artist_appearances(exploded).sort_values(ascending=False)
cum_share = counts.cumsum() / counts.sum() * 100
artist_rank_pct = np.arange(1, len(counts) + 1) / len(counts) * 100
fig, ax = plt.subplots(figsize=(7, 6))
ax.plot(artist_rank_pct, cum_share.values, color=ATLANTIC_RED, linewidth=2.5)
ax.plot([0, 100], [0, 100], color=ATLANTIC_GREY, linestyle="--", linewidth=1)
ax.set_xlabel("Cumulative % of artists (ranked by dominance)")
ax.set_ylabel("Cumulative % of chart appearances")
ax.set_title("Artist Concentration Curve\n(Top-5 artists = {:.1f}% of all appearances)".format(
    an.artist_concentration_index(exploded, 5)["top_n_share_pct"]))
ax.set_xlim(0, 100); ax.set_ylim(0, 100)
savefig(fig, "02_concentration_curve")

# 3. Solo vs collaboration
sc = an.solo_vs_collab(df)
fig, ax = plt.subplots(figsize=(5, 5))
ax.pie(sc.values, labels=[f"{k}\n{v:,} ({v/sc.sum()*100:.1f}%)" for k, v in sc.items()],
       colors=[ATLANTIC_NAVY, ATLANTIC_RED], startangle=90,
       wedgeprops={"edgecolor": "white", "linewidth": 1.5})
ax.set_title("Solo vs. Collaborative Tracks")
savefig(fig, "03_solo_vs_collab")

# 4. Collaboration ratio by rank group
cbr = an.collab_by_rank_group(df)
fig, ax = plt.subplots(figsize=(7, 5))
ax.bar(cbr.index, cbr.values, color=ATLANTIC_TEAL)
ax.set_ylabel("Collaboration share (%)")
ax.set_title("Collaboration Prevalence by Chart Position")
for i, v in enumerate(cbr.values):
    ax.text(i, v + 0.4, f"{v:.1f}%", ha="center")
savefig(fig, "04_collab_by_rank")

# 5. Top collaborator pairs (horizontal bar chart)
# NOTE: generated by the dedicated make_collab_chart.py script. A node-link
# network diagram was tried first, but the underlying data (16 mostly-
# disconnected pairs/small clusters) doesn't have real network structure to
# show, so it fought overlap/legibility problems for no analytical payoff.
# A sorted bar chart of pair frequency answers the same question directly
# and has zero overlap risk by construction.
import subprocess
print("Generating top-collaborator-pairs chart (see make_collab_chart.py)...")
subprocess.run([sys.executable, "src/make_collab_chart.py"], check=True, cwd=".")

# 6. Explicit vs clean share
es = an.explicit_share(df)
fig, ax = plt.subplots(figsize=(5, 5))
ax.pie(es.values, labels=[f"{k}\n{v:.1f}%" for k, v in es.items()],
       colors=[ATLANTIC_RED, ATLANTIC_TEAL], startangle=90,
       wedgeprops={"edgecolor": "white", "linewidth": 1.5})
ax.set_title("Explicit vs. Clean Content Share")
savefig(fig, "06_explicit_share")

# 7. Explicit content by rank
ebr = an.explicit_by_rank(df)
fig, ax = plt.subplots(figsize=(7, 5))
ax.bar(ebr.index, ebr.values, color=ATLANTIC_RED)
ax.set_ylabel("Explicit share (%)")
ax.set_title("Explicit Content Distribution by Chart Position")
for i, v in enumerate(ebr.values):
    ax.text(i, v + 0.4, f"{v:.1f}%", ha="center")
savefig(fig, "07_explicit_by_rank")

# 8. Explicit share over time
eot = an.explicit_over_time(df)
fig, ax = plt.subplots(figsize=(9, 5))
ax.plot(eot.index, eot.values, color=ATLANTIC_RED, marker="o", linewidth=2)
ax.set_ylabel("Explicit share (%)")
ax.set_title("Explicit Content Share Over Time (Monthly)")
fig.autofmt_xdate()
savefig(fig, "08_explicit_over_time")

# 9. Album type share
ats = an.album_type_share(df)
fig, ax = plt.subplots(figsize=(5, 5))
ax.pie(ats.values, labels=[f"{k.title()}\n{v:.1f}%" for k, v in ats.items()],
       colors=PALETTE, startangle=90, wedgeprops={"edgecolor": "white", "linewidth": 1.5})
ax.set_title("Release Format Share: Single vs. Album vs. Compilation")
savefig(fig, "09_album_type_share")

# 10. Release format by rank group
rfr = an.release_format_by_rank(df)
fig, ax = plt.subplots(figsize=(8, 5))
rfr[["single", "album", "compilation"]].plot(
    kind="bar", stacked=True, ax=ax, color=[ATLANTIC_RED, ATLANTIC_NAVY, ATLANTIC_GOLD])
ax.set_ylabel("Share (%)")
ax.set_title("Release Format by Chart Position")
ax.legend(title="Format", bbox_to_anchor=(1.02, 1), loc="upper left")
plt.xticks(rotation=0)
savefig(fig, "10_release_format_by_rank")

# 11. Duration distribution
dd = an.duration_distribution(df)
fig, ax = plt.subplots(figsize=(7, 5))
ax.bar(dd.index, dd.values, color=ATLANTIC_GOLD)
ax.set_ylabel("Share of entries (%)")
ax.set_title("Track Duration Distribution")
plt.xticks(rotation=15, ha="right")
for i, v in enumerate(dd.values):
    ax.text(i, v + 0.4, f"{v:.1f}%", ha="center")
savefig(fig, "11_duration_distribution")

# 12. Duration vs popularity bucket
dvp = an.duration_vs_popularity(df)
fig, ax = plt.subplots(figsize=(7, 5))
ax.bar(dvp.index.astype(str), dvp.values, color=ATLANTIC_TEAL)
ax.set_ylabel("Average duration (seconds)")
ax.set_title("Average Track Duration by Popularity Quartile")
ax.set_ylim(min(dvp.values) - 10, max(dvp.values) + 10)
for i, v in enumerate(dvp.values):
    ax.text(i, v + 1, f"{v:.0f}s", ha="center")
savefig(fig, "12_duration_vs_popularity")

# 13. Domestic vs International
dvi = an.domestic_vs_international(exploded)
fig, ax = plt.subplots(figsize=(5, 5))
ax.pie(dvi.values, labels=[f"{k}\n{v:.1f}%" for k, v in dvi.items()],
       colors=[ATLANTIC_NAVY, ATLANTIC_RED, ATLANTIC_GREY], startangle=90,
       wedgeprops={"edgecolor": "white", "linewidth": 1.5})
ax.set_title("UK / Domestic vs. International Artist Share\n(share of chart appearances)")
savefig(fig, "13_domestic_vs_international")

# 14. Domestic vs International by rank group
dvir = an.domestic_vs_international_by_rank(df, exploded)
fig, ax = plt.subplots(figsize=(8, 5))
dvir[["UK / Domestic", "International"]].plot(
    kind="bar", ax=ax, color=[ATLANTIC_NAVY, ATLANTIC_RED])
ax.set_ylabel("Share (%)")
ax.set_title("UK / Domestic vs. International Share by Chart Position")
plt.xticks(rotation=0)
ax.legend(bbox_to_anchor=(1.02, 1), loc="upper left")
savefig(fig, "14_domestic_intl_by_rank")

# 15. Unique artists per day over time (diversity trend)
uapd = an.unique_artists_per_day(exploded)
fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(uapd.index, uapd.values, color=ATLANTIC_NAVY, linewidth=1)
ax.plot(uapd.index, uapd.rolling(30).mean(), color=ATLANTIC_RED, linewidth=2.5, label="30-day rolling avg")
ax.set_ylabel("Unique artists that day")
ax.set_title("Daily Playlist Artist Diversity Over Time")
ax.legend()
fig.autofmt_xdate()
savefig(fig, "15_diversity_trend")

# 16. Domestic vs international trend over time
dit = an.domestic_vs_international_trend(exploded)
fig, ax = plt.subplots(figsize=(9, 5))
dit[["UK / Domestic", "International"]].plot(ax=ax, color=[ATLANTIC_NAVY, ATLANTIC_RED], marker="o")
ax.set_ylabel("Share of appearances (%)")
ax.set_title("UK / Domestic vs. International Share Over Time (Quarterly)")
fig.autofmt_xdate()
savefig(fig, "16_domestic_intl_trend")

print("\nAll figures generated in", OUT)
