[theme]
primaryColor = "#737D52"
backgroundColor = "#EEE9DC"
secondaryBackgroundColor = "#F5F1E7"
textColor = "#151513"
font = "sans serif"

[client]
toolbarMode = "developer"

[server]
headless = true
